### ISSUE TITLE
部会・委員会資料の編集ができない

### ISSUE THREAD

**Issue by shimada-yusei** [kumano-dormitory/kumanodocs-hanami#140]
# 概要
管理者向けページ→寮生向けの資料一覧　と進むとすでに共有されている資料を編集することができるがその際，一度投稿したPDF資料の編集画面に入り，新しいPDFに置き換えようとすると500エラーを吐く．
新しく投稿する際にはエラーは発生しない．

# 試したこと

- 特定の文責者による投稿だけがエラーになるか
- タイトルを変更して変更を保存してもエラーになるか
- 変更前と同じPDFファイルを投稿してもエラーになるか
- PDFのサイズは関係あるか
- 変更後のPDFを指定しなくてもエラーになるか

以上のことを試したがすべての場合でエラーになった．

**Comment by bo40** [comment]
こんばんは。
まだ、熊野寮のサーバにログインできたのでエラーログを見てみました。(`sudo docker logs kumano-docker-kumanodocs-hanami-1`で見れるやつです）
多分、以下のログがエラーを指していると思うので、`/app/apps/admin/controllers/docs/update.rb`の38行目あたりを確認してみると良いと思う。
おそらく`params`から`:document`や`:data`といったSymbolを使ってハッシュテーブルから値を取り出そうとしているところで、配列が渡ってきていてエラーになっていると思われる。
調べても分からなかったらサポートするので連絡ちょうだい。
```
TypeError: no implicit conversion of Symbol into Integer
	/app/apps/admin/controllers/docs/update.rb:38:in `[]'
	/app/apps/admin/controllers/docs/update.rb:38:in `call'
	/usr/local/bundle/gems/hanami-controller-1.3.3/lib/hanami/action/callbacks.rb:195:in `call'
	/usr/local/bundle/gems/hanami-controller-1.3.3/lib/hanami/action/callable.rb:71:in `block in call'
	/usr/local/bundle/gems/hanami-controller-1.3.3/lib/hanami/action/throwable.rb:129:in `block in _rescue'
	/usr/local/bundle/gems/hanami-controller-1.3.3/lib/hanami/action/throwable.rb:127:in `catch'
	/usr/local/bundle/gems/hanami-controller-1.3.3/lib/hanami/action/throwable.rb:127:in `_rescue'
	/usr/local/bundle/gems/hanami-controller-1.3.3/lib/hanami/action/callable.rb:67:in `call'
	/usr/local/bundle/gems/hanami-router-1.3.2/lib/hanami/routing/endpoint.rb:101:in `call'
	/usr/local/bundle/gems/http_router-0.11.2/lib/http_router.rb:193:in `process_destination_path'
	(eval):1025:in `call'
	/usr/local/bundle/gems/http_router-0.11.2/lib/http_router.rb:288:in `raw_call'
	/usr/local/bundle/gems/hanami-router-1.3.2/lib/hanami/routing/http_router.rb:160:in `raw_call'
	/usr/local/bundle/gems/hanami-router-1.3.2/lib/hanami/router.rb:1019:in `call'
	/usr/local/bundle/gems/rack-2.2.3.1/lib/rack/session/abstract/id.rb:266:in `context'
	/usr/local/bundle/gems/rack-2.2.3.1/lib/rack/session/abstract/id.rb:260:in `call'
	/usr/local/bundle/gems/rack-2.2.3.1/lib/rack/builder.rb:244:in `call'
	/usr/local/bundle/gems/hanami-1.3.5/lib/hanami/middleware_stack.rb:52:in `call'
	/usr/local/bundle/gems/hanami-1.3.5/lib/hanami/application.rb:169:in `call'
	/usr/local/lib/ruby/2.6.0/delegate.rb:83:in `method_missing'
	/usr/local/bundle/gems/http_router-0.11.2/lib/http_router.rb:193:in `process_destination_path'
	(eval):72:in `call'
	/usr/local/bundle/gems/http_router-0.11.2/lib/http_router.rb:288:in `raw_call'
	/usr/local/bundle/gems/hanami-router-1.3.2/lib/hanami/routing/http_router.rb:160:in `raw_call'
	/usr/local/bundle/gems/hanami-router-1.3.2/lib/hanami/router.rb:1019:in `call'
	/usr/local/bundle/gems/rack-2.2.3.1/lib/rack/method_override.rb:24:in `call'
	/usr/local/bundle/gems/rack-2.2.3.1/lib/rack/content_length.rb:17:in `call'
	/usr/local/bundle/gems/rack-2.2.3.1/lib/rack/common_logger.rb:38:in `call'
	/usr/local/bundle/gems/hanami-1.3.5/lib/hanami/app.rb:44:in `call'
	/usr/local/bundle/gems/puma-5.6.4/lib/puma/configuration.rb:252:in `call'
	/usr/local/bundle/gems/puma-5.6.4/lib/puma/request.rb:77:in `block in handle_request'
	/usr/local/bundle/gems/puma-5.6.4/lib/puma/thread_pool.rb:340:in `with_force_shutdown'
	/usr/local/bundle/gems/puma-5.6.4/lib/puma/request.rb:76:in `handle_request'
	/usr/local/bundle/gems/puma-5.6.4/lib/puma/server.rb:441:in `process_client'
	/usr/local/bundle/gems/puma-5.6.4/lib/puma/thread_pool.rb:147:in `block in spawn_thread'
```
